name: django-challenge
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.11
  - django=5.2
  - chromadb
  - openai
  - langchain
  - langchain[openai]
  - pillow
  - pytesseract
  - sentence-transformers